HTTP/1.1 200 OK
access-control-allow-credentials: true
access-control-allow-origin: 
cf-cache-status: DYNAMIC
cf-ray: 8cc4ddba79f6e7e7-DFW
connection: keep-alive
content-length: 44
content-type: application/json; charset=UTF-8
date: Wed, 02 Oct 2024 12:58:49 GMT
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=imfSlV%2Fb23mau1Gvq9PuI25XIMvrxCGtA5muzJgE%2FcBEXKNMVNyZlV3ekE%2Fm6tygl%2Bz73r0UxkCaQ%2BtNvloWiiFYJGSXX%2B8U6owaw9VX1z3%2F0YDgL0bDIVoJy1uG2a7uCQ%3D%3D"}],"group":"cf-nel","max_age":604800}
server: cloudflare
vary: Origin

{
  "url": "https://i.waifu.pics/AoPMBb_.jpeg"
}